### ISSUE TITLE
Error uploading archive to storage: The object exceeded the maximum allowed size

### ISSUE THREAD

**Issue by DRMacIver** [TheExGenesis/community-archive#94]
I get this error message when trying to upload my archive (which is 512MB):

> Error uploading archive to storage: The object exceeded the maximum allowed size

(I can provide more details if needed, but I'm not sure what would be useful, and probably the problem has some fairly straightforward underlying cause)

**Comment by TheExGenesis** [comment]
Size limit increased! Try again please?

**Comment by TheExGenesis** [comment]
Size limit increased! Try again please? @DRMacIver

**Comment by TheExGenesis** [comment]
Please try again? Thanks for being patient @DRMacIver

**Comment by DRMacIver** [comment]
"An error occurred while processing archive"

Looking at the developer console, I see:

```
862-b7b0bc2f6ad93dcd.js:1 Error loading the archive: SyntaxError: Bad escaped character in JSON at position 47092891 (line 1 column 47092892)
    at parse (<anonymous>)
    at 961-40c93f44ca936ba5.js:1:13752
    at Array.reduce (<anonymous>)
    at 961-40c93f44ca936ba5.js:1:13738
    at 961-40c93f44ca936ba5.js:1:17220
    at Array.flatMap (<anonymous>)
    at 961-40c93f44ca936ba5.js:1:17167
    at Array.map (<anonymous>)
    at ee (961-40c93f44ca936ba5.js:1:17084)
    at et (961-40c93f44ca936ba5.js:1:17599)
```

**Comment by TheExGenesis** [comment]
dm'd you on twitter, thanks for persisting!

**Comment by TheExGenesis** [comment]
@DRMacIver I really think I fixed it this time @DRMacIver, there was a bug that only errored for accounts with capital letters in their usernames 😅

**Comment by DRMacIver** [comment]
@TheExGenesis Nope, afraid not (or if you have the fix isn't deployed). Still getting the same error. I've shared the archive with you now on Google drive.
